M3_Project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('category.urls')),
    path('',include('stylemaster.urls')),
]

category/urls.py
from django.urls import path
from django.contrib.auth.views import login,logout
from category import views

urlpatterns=[
    path('login/',login,{'template_name':'category/login.html'},name='login'),
    path('register/',views.register,name='register'),
    path('query/',views.query,name='query')
]

stylemaster/urls.py
from django.urls import path
from stylemaster import views
from M3_Project import settings
from django.conf.urls.static import static

urlpatterns=[
    path('sample/', views.sample, name='sample'),
    path('stylemaster/', views.style, name='style'),
    path('stylefull/', views.stylefull, name='stylefull'),
    path('fabric/', views.fabric, name='fabric'),
    path('trims/', views.trims, name='trims'),
    
    path('preview/',views.preview,name='preview'),
    path('BOM_selection/',views.bom_select,name='bom_select'),
    path('bomfill/',views.bomfill,name='bomfill'),
    path('Bill_of_materials/',views.bom,name='bom'),
    path('updatefab/<int:pk>',views.updatefab.as_view(),name='updatefab'),
    path('updatetri/<int:pk>',views.updatetri.as_view(),name='updatetri'),
    path('update/<int:pk>',views.update.as_view(),name='update'),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

stylemaster/models.py
from django.db import models
from datetime import date
# Create your models here.
class Approver(models.Model):
    approve=models.CharField(max_length=100)

    def __str__(self):
        return str(self.approve)

class ProductionMerchant(models.Model):
    production_mrchant=models.CharField(max_length=100)

    def __str__(self):
        return str(self.production_mrchant)

class FactoryMerchant(models.Model):
    factory_mrchant=models.CharField(max_length=100)

    def __str__(self):
        return str(self.factory_mrchant)

class PDMerchant(models.Model):
    pd_mrchant=models.CharField(max_length=100)

    def __str__(self):
        return str(self.pd_mrchant)

class CustomGroup(models.Model):
    custom_grp=models.CharField(max_length=100)

    def __str__(self):
        return str(self.custom_grp)

class Sample(models.Model):
    def number():
        no = Sample.objects.count()
        if no == None:
            return 1
        else:
            return no + 1

    sample_no = models.IntegerField(unique=True, default=number)
    pch=models.CharField(max_length=10)
    style=models.CharField(max_length=100)
    desc=models.TextField(max_length=2500)
    sketch=models.FileField(upload_to="static/images")

    def __str__(self):
        return str(self.pch)

class Stylemaster(models.Model):
    def number():
        no = Stylemaster.objects.count()
        if no == None:
            return 1
        else:
            return no + 1

    style_no = models.IntegerField(unique=True, default=number)
    item_no=models.ForeignKey(Sample,on_delete=models.CASCADE)
    style=models.CharField(max_length=100)
    type=models.CharField(max_length=100)
    brand=models.CharField(max_length=100)
    category=models.CharField(max_length=100)
    item_group=models.CharField(max_length=100)
    season=models.CharField(max_length=100,null=True,blank=True)
    responsible=models.CharField(max_length=100)
    approver=models.ForeignKey(Approver,on_delete=models.CASCADE)
    product_designer=models.CharField(max_length=100,null=True,blank=True)
    production_merchant=models.ForeignKey(ProductionMerchant,on_delete=models.CASCADE)
    pd_merchant=models.ForeignKey(PDMerchant,on_delete=models.CASCADE,null=True,blank=True)
    factory_merchant=models.ForeignKey(FactoryMerchant,on_delete=models.CASCADE,null=True,blank=True)
    sales_person=models.CharField(max_length=100)
    basic_uom=models.CharField(max_length=100)
    alt_uom=models.CharField(max_length=100,null=True,blank=True)
    conversion_factor=models.CharField(max_length=100,null=True,blank=True)
    currency=models.CharField(max_length=100)
    sales_price=models.CharField(max_length=100)
    sale_price_qty=models.CharField(max_length=100,null=True,blank=True)
    buying_house_commission=models.CharField(max_length=100,null=True,blank=True)
    licence=models.CharField(max_length=100,null=True,blank=True)
    custom_group=models.ForeignKey(CustomGroup,on_delete=models.CASCADE,null=True,blank=True)
    national_dbk=models.DecimalField(default=0,max_digits=7,decimal_places=4,null=True,blank=True)
    rosl_group=models.CharField(max_length=100,null=True,blank=True)
    propertys=models.CharField(max_length=100,null=True,blank=True)
    order_confirmation_date=models.DateField(("Date"), default=date.today,null=True,blank=True)
    pcd=models.DateField(null=True,blank=True)
    ex_factory_date=models.DateField(null=True,blank=True)

    def __str__(self):
        return str(self.item_no)


FB = [('Fabric00001', 'Fabric00001'),
      ('Fabric00002', 'Fabric00002'),
      ]


class Fabric(models.Model):
    def number():
        no = Fabric.objects.count()
        if no == None:
            return 1
        else:
            return no + 1

    fabric_no = models.IntegerField(unique=True, default=number)
    fabric_item_no = models.ForeignKey(Stylemaster,on_delete=models.CASCADE)
    quality = models.CharField(max_length=20, null=True, blank=True)
    composition = models.CharField(max_length=30)
    weave = models.CharField(max_length=20, null=True, blank=True)
    count = models.CharField(max_length=5, null=True, blank=True)
    construction = models.CharField(max_length=10)
    types = models.CharField(max_length=50, null=True, blank=True)
    fabric_code = models.CharField(max_length=15, choices=FB)

    def __str__(self):
        return str(self.fabric_item_no)


TM = [('Trim00001', 'Trim00001'),
      ('Trim00002', 'Trim00002'),
      ]

''
class Trims(models.Model):
    def number():
        no = Trims.objects.count()
        if no == None:
            return 1
        else:
            return no + 1

    trim_no = models.IntegerField(unique=True, default=number)
    trim_item_no = models.ForeignKey(Stylemaster, on_delete=models.CASCADE)
    quality = models.CharField(max_length=20, null=True, blank=True)
    composition = models.CharField(max_length=30)
    size = models.CharField(max_length=5)
    color = models.CharField(max_length=10, null=True, blank=True)
    construction = models.CharField(max_length=10)
    types = models.CharField(max_length=50, null=True, blank=True)
    trim_code = models.CharField(max_length=10, choices=TM)

    def __str__(self):
        return str(self.trim_item_no)


class BOM(models.Model):
    item_no=models.ForeignKey(Stylemaster,on_delete=models.CASCADE)
    fabconsumption=models.CharField(max_length=20)
    fabquality=models.CharField(max_length=20)
    fabwidth=models.CharField(max_length=10)
    fabunit=models.CharField(max_length=5)
    consumption=models.DecimalField(max_digits=12,decimal_places=5)
    fabrate=models.DecimalField(max_digits=12,decimal_places=5)
    trims=models.CharField(max_length=20)
    trimquality=models.CharField(max_length=20)
    trimspecific=models.CharField(max_length=10)
    trimunit=models.CharField(max_length=5)
    trimconsumption=models.DecimalField(max_digits=12,decimal_places=5)
    trimrate=models.DecimalField(max_digits=12,decimal_places=5)

    def __str__(self):
        return str(self.item_no)

stylemaster/forms.py
from django import forms

from .models import *


class Sam(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['sample_no'].widget.attrs['readonly'] = True

    class Meta:
        model = Sample
        fields = ('sample_no', 'pch', 'style', 'desc', 'sketch')


class Style(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['style_no'].widget.attrs['readonly'] = True

    class Meta:
        model = Stylemaster
        fields = ('style_no', 'item_no')


class StyleFull(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['style_no'].widget.attrs['readonly'] = True

    class Meta:
        model = Stylemaster
        fields = ('style_no', 'item_no', 'style', 'type', 'brand', 'category',
                  'item_group', 'season', 'responsible',
                  'approver', 'product_designer', 'production_merchant',
                  'pd_merchant', 'factory_merchant', 'sales_person', 'basic_uom',
                  'alt_uom', 'conversion_factor', 'currency', 'sales_price',
                  'sale_price_qty', 'buying_house_commission', 'licence',
                  'custom_group', 'national_dbk', 'rosl_group', 'propertys',
                  'order_confirmation_date', 'pcd', 'ex_factory_date')

class FabricForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['fabric_no'].widget.attrs['readonly'] = True

    class Meta:
        model = Fabric
        fields = ('fabric_no', 'fabric_item_no', 'quality', 'composition',
                  'weave', 'count', 'construction', 'types', 'fabric_code')


class TrimsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['trim_no'].widget.attrs['readonly'] = True

    class Meta:
        model = Trims
        fields = ('trim_no', 'trim_item_no', 'quality', 'composition',
                  'size', 'color', 'construction', 'types', 'trim_code')

class Bom(forms.ModelForm):
    class Meta:
        model = BOM
        fields = ('item_no','fabconsumption','fabquality','fabwidth','fabunit','consumption','fabrate',
                  'trims','trimquality','trimspecific','trimunit','trimconsumption','trimrate')


class Bomselect(forms.ModelForm):
    class Meta:
        model = Stylemaster
        fields = ('item_no',)

stylemaster/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib import  messages
from django.http import HttpResponse
from stylemaster.models import *
# Create your views here.
from .forms import *
from django.views.generic.edit import CreateView,DeleteView,UpdateView
from django.urls import reverse_lazy
import mathfilters



def sample(request):
    if (request.method == 'POST'):
        form = Sam(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponse('<h1>Your Sample is recorded</h1>')
        else:
            messages.error(request, "Error")

    else:
        form = Sam()
    return render(request, 'stylemaster/sample.html', {'form': form})


def style(request):
    if (request.method == 'POST'):
        form = Style(request.POST)
        if form.is_valid():
            s = Sample.objects.all()
            global item
            item = request.POST.get('item_no')
            for i in s:
                if (str(i.id) == item):
                    global value1
                    global value2
                    global value3
                    value1 = i.style
                    value2 = i.desc
                    value3 = i.sketch
            return redirect('/stylefull')
            # return render(request,'stylemaster/stylefull.html',context)
        else:
            messages.error(request, "Error")
            # form['category'].data=i.style
            # form['type'].data=i.desc
            # item=request.GET.values()
            # item=form['item_no'].data
            # item=form['item_no'].field.value
            # form.save()

    else:
        form = Style()
    return render(request, 'stylemaster/style_master.html', {'form': form})


def stylefull(request):
    if (request.method == 'POST'):
        form = StyleFull(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/fabric')
        else:
            messages.error(request, "Error")
    else:
        global value1
        global value2
        global value3
        global item
        form = StyleFull(initial={'item_no': item, 'style': value1, 'type': value2,'sketch':value3})
    return render(request, 'stylemaster/stylefull.html', {'form': form})

def fabric(request):
    if (request.method == 'POST'):
        form = FabricForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/trims')
        else:
            messages.error(request, "Error")

    else:
        global item
        form = FabricForm(initial={'fabric_item_no':item})
    return render(request, 'stylemaster/fabric.html', {'form': form})

def trims(request):
    if (request.method == 'POST'):
        form = TrimsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/preview')
        else:
            messages.error(request, "Error")

    else:
        global  item
        form = TrimsForm(initial={'trim_item_no':item})
    return render(request, 'stylemaster/trim.html', {'form': form})

def preview(request):
    global item
    a=Stylemaster.objects.filter(item_no=item)
    b=Fabric.objects.filter(fabric_item_no=item)
    c=Trims.objects.filter(trim_item_no=item)
    return render(request, 'stylemaster/preview.html',{'a':a,'b':b,'c':c})

class update(UpdateView):
    model = Stylemaster
    fields = ('style_no', 'item_no', 'style', 'type', 'brand', 'category',
              'item_group', 'season', 'responsible',
              'approver', 'product_designer', 'production_merchant',
              'pd_merchant', 'factory_merchant', 'sales_person', 'basic_uom',
              'alt_uom', 'conversion_factor', 'currency', 'sales_price',
              'sale_price_qty', 'buying_house_commission', 'licence',
              'custom_group', 'national_dbk', 'rosl_group', 'propertys',
              'order_confirmation_date', 'pcd', 'ex_factory_date')
    def fun(self,request):
        global item
        item = request.POST.get('item_no')
        print(item)
        return super().fun(request)
    template_name = "stylemaster/stylefull.html"
    success_url = reverse_lazy('preview')

class updatefab(UpdateView):
    model=Fabric
    fields=('fabric_no','fabric_item_no','quality','composition','weave',
                'count','construction','types','fabric_code')
    def fun(self,request):
        global item
        item = request.POST.get('item_no')
        print(item)
        return super().fun(request)
    template_name = "stylemaster/fabric.html"
    success_url = reverse_lazy('preview')

class updatetri(UpdateView):
    model=Trims
    fields=('trim_no','trim_item_no','quality','composition','size',
                'color','construction','types','trim_code')
    def fun(self,request):
        global item
        item = request.POST.get('item_no')
        print(item)
        return super().fun(request)
    template_name = "stylemaster/trim.html"
    success_url = reverse_lazy('preview')

'''
def user_edit(request):

    if request.method == 'POST':
        user_form = Stylemaster(request.POST, instance=request.user)
        profile_form = FabricForm(request.POST, instancel=request.user.profile)

        if all([user_form.is_valid(), profile_form.is_valid()]):
            user = user_form.save()
            profile = profile_form.save()
            return redirect(user)

    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)

    return render(request, 'accounts/user_form.html', {
        'user_form': user_form,
        'profile_form': profile_form,
    })'''

def bom_select(request):
    if (request.method == 'POST'):
        form = Bomselect(request.POST)
        if form.is_valid():
            s = Sample.objects.all()
            global items
            items = request.POST.get('item_no')

            return redirect('/Bill_of_materials')
            #return render(request,'stylemaster/bom.html')
        else:
            messages.error(request, "Error")

    else:
        form = Bomselect()
    return render(request, 'stylemaster/bom_select.html', {'form': form})

def bom(request):
    global items
    a = Stylemaster.objects.filter(item_no=items)
    b = Fabric.objects.filter(fabric_item_no=items)
    c = Trims.objects.filter(trim_item_no=items)
    d = BOM.objects.filter(item_no=items)

    return render(request, 'stylemaster/bom.html', {'a': a, 'b': b, 'c': c,'d':d})

def bomfill(request):
    if (request.method == 'POST'):
        form = Bom(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/bomfill')
        else:
            messages.error(request, "Error")

    else:

        form = Bom()
    return render(request, 'stylemaster/bom_fill.html', {'form': form})

stylemaster/templates/stylemaster/base.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
	 <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>


<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="{% url 'sample' %}">Sample</a></li>
      <li><a href="{% url 'style' %}">Style Master</a></li>
      <li><a href="{% url 'fabric' %}">Add Fabric</a></li>
        <li><a href="{% url 'trims' %}">Add Trim</a></li>
    </ul>
  </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

stylemaster/templates/stylemaster/bom.html
{% extends 'stylemaster/base.html' %}
{% block body %}
<h1 style="color:#ff4c17;">Summary</h1>
    {% for i in a %}
 <div class="col-md-2"> Style : </div> <div class="col-md-2 btn-primary">    {{ i.style }}</div>

<div class="col-md-2"> Category : </div> <div class="col-md-2 btn-primary">  {{ i.category }}</div>

  <div class="col-md-2"> Color : </div> <div class="col-md-2 btn-primary">    {{ i.style }}</div>

<div class="col-md-2"> Size : </div> <div class="col-md-2 btn-primary">  {{ i.category }}</div>

    <div class="col-md-2"> Style : </div> <div class="col-md-2 btn-primary">    {{ i.style }}</div>

<div class="col-md-2"> Category : </div> <div class="col-md-2 btn-primary">  {{ i.category }}</div>

{% endfor %}

<br><br>{% load mathfilters %}
    <h2 align="center" style="color:#ff4c17;">Bill of materials</h2>
<h2 style="color:#ff4c17;">Fabrics Description</h2>
  <table class="table table-bordered table-striped table-hover table-responsive" >
<thead class="thead-dark">
<tr  class="btn-primary"><th style="text-align: center;">Fabric Name</th >
    <th style="text-align: center;">Quality</th><th style="text-align: center;">Width</th>
    <th style="text-align: center;">Unit</th><th style="text-align: center;">Consumption</th>
    <th style="text-align: center;">Rate</th><th style="text-align: center;">Cost</th></tr></thead>
   {% for m in d %}
       <tr style="text-align: center">
<td >{{ m.fabconsumption}}</td>
       <td>{{ m.fabquality }}</td>
       <td>{{ m.fabwidth }}</td>
       <td>{{ m.fabunit }}</td>
       <td>{{ m.consumption }}</td>
       <td>{{ m.fabrate }}</td>
       <td>  {{m.consumption|mul:m.fabrate}}</td>
       </tr>
{% endfor %}
</table>


    <br>
    <br>



 <h2 style="color:#ff4c17;">Trims Description</h2>
  <table class="table table-bordered table-striped table-hover table-responsive" >
<thead class="thead-dark">
<tr  class="btn-primary"><th style="text-align: center;">Trims Name</th >
    <th style="text-align: center;">Quality</th><th style="text-align: center;">Specification</th>
    <th style="text-align: center;">Unit</th><th style="text-align: center;">Consumption</th>
    <th style="text-align: center;">Rate</th><th style="text-align: center;">Cost</th></tr></thead>
   {% for m in d %}
       <tr style="text-align: center">
<td >{{ m.trims}}</td>
       <td>{{ m.trimquality }}</td>
       <td>{{ m.trimspecific }}</td>
       <td>{{ m.trimunit }}</td>
       <td>{{ m.trimconsumption }}</td>
       <td>{{ m.trimrate }}</td>
       <td> {{m.trimconsumption|mul:m.trimrate}}</td>
       </tr>
{% endfor %}
</table>
    <br>
    <br>
{% endblock %}

stylemaster/templates/stylemaster/bom_fill.html
{% extends 'stylemaster/base.html' %}
{% block body %}
     <div class="container">
    <div class="container">
    <div class="col-sm-6">
    <div class=" panel panel-primary">
    <div class="panel-heading"><h3>Fabrics & Trims</h3></div>
    <div class="panel-body">
<form method="post" enctype="multipart/form-data">
    <h2>Description</h2>
{% csrf_token %}
<table>
    {{ form.as_table }}
</table>
<button type="Submit">Submit</button></form>
         </div>
    </div>
    </div>
    </div>
</div>
{% endblock %}

stylemaster/templates/stylemaster/bom_select.html
{% extends 'stylemaster/base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

 <button type="submit" value="Style" >Submit</button>
</form>

{% endblock %}

stylemaster/templates/stylemaster/fabric.html
{% extends 'stylemaster/base.html' %}

{% block body %}
     <div class="container">
    <div class="container">
    <div class="col-sm-6">
    <div class="panel panel-primary">
    <div class="panel-heading"><h3>Fabric</h3></div>
    <div class="panel-body">
<form method="post">
	{% csrf_token %}
	<table>
    {{ form.as_table }}

	</table>
<button type="Submit" value="Fabric">Submit</button>
</form>
         </div>
    </div>
    </div>
    </div>
</div>
{% endblock %}

stylemaster/templates/stylemaster/sample.html
{% extends 'stylemaster/base.html' %}

{% block body %}
     <div class="container">
    <div class="container">
    <div class="col-sm-6">
    <div class=" panel panel-primary">
    <div class="panel-heading"><h3>Sample</h3></div>
    <div class="panel-body">
<form method="post" enctype="multipart/form-data">
{% csrf_token %}

    {{ form.as_p }}

<button type="Submit">Submit</button></form>
         </div>
    </div>
    </div>
    </div>
</div>
{% endblock %}

stylemaster/templates/stylemaster/style_master.html
{% extends 'stylemaster/base.html' %}

{% block body %}
    <div class="container">
    <div class="container">
    <div class="col-sm-6">
    <div class="panel panel-primary">
    <div class="panel-heading"><h3>StyleMaster</h3></div>
    <div class="panel-body">
 <form enctype="multipart/form-data" method="POST">
 
                {% csrf_token %}
                {% for field in form %}
				
					{% if forloop.counter == 3 %}
						
					{% endif %}
                    {{ field.label }} {{ field }}
                    {% if forloop.counter|divisibleby:"2" %}
                        <br>
						<br>
                    {% endif %}
					
                {% endfor %}
                <button type="submit" value="Style" >Submit</button>
            </form>
        </div>
    </div>
    </div>
    </div>
</div>
{% endblock %}

stylemaster/templates/stylemaster/stylefull.html
{% extends 'stylemaster/base.html' %}

{% block body %}

     <div class="container">
    <div class="container">
    <div class="col-sm-6">
    <div class="panel panel-primary">
    <div class="panel-heading"><h3>StyleMaster</h3></div>
    <div class="panel-body">
 <form enctype="multipart/form-data" method="POST">
	
                {% csrf_token %}
                {% for field in form %}
					{% if forloop.counter == 3 %}
					{% endif %}
                    {{ field.label }} {{ field }}
                    {% if forloop.counter|divisibleby:"2" %}
                        <br>
						<br>
                    {% endif %}
				
                {% endfor %}
                <button type="submit" value="Submit" >Submit</button>
</form>

       </div>
    </div>
    </div>
    </div>
</div>
<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/themes/base/jquery-ui.css" type="text/css" media="all" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.min.js" type="text/javascript"></script>
    <script>
  $(function() {

  $( "#id_pcd" ).datepicker();
  $( "#id_order_confirmation_date" ).datepicker();
      $("#id_ex_factory_date").datepicker();
  });
</script>
{% endblock %}

stylemaster/templates/stylemaster/trim.html
{% extends 'stylemaster/base.html' %}

{% block body %}
     <div class="container">
    <div class="container">
    <div class="col-sm-6">
    <div class="panel panel-primary">
    <div class="panel-heading"><h3>Trim</h3></div>
    <div class="panel-body">
<form method="post">
	{% csrf_token %}
	<table>
    {{ form.as_table }}

	</table>
<button type="Submit" value="Trims">Submit</button>
</form>
         </div>
    </div>
    </div>
    </div>
</div>
{% endblock %}